### ISSUE TITLE
[FEATURE REQUEST] - Allow class timings and Firefox profile to be edited with configuration file

### ISSUE THREAD

**Issue by jyuvaraj03** [sooryaprakash31/GMeet-Bot#2]
The way the code is setup now, the class timings and Firefox profile cannot be edited without changing the main source file. I think this could easily be achieved by using the config.ini file and reading from that (just like how authentication credentials are read from it). 

I'll submit a pull request to implement this feature soon.

**Comment by sooryaprakash31** [comment]
Sure. Go ahead!

**Comment by jyuvaraj03** [comment]
The class timings still cannot be edited with the config file. So, I'd suggest to either leave this issue open or edit this issue to focus only on the firefox profile problem.

**Comment by sooryaprakash31** [comment]
Read the class timings from schedule.csv header. The recently added feature fixes this issue.
